#cloud-config

groups:
  - docker
users:
  - default
  # the docker service account
  - name: docker-service
    groups: docker
package_upgrade: true
packages:
  - wget
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - docker.io
  - kubelet
  - kubectl
  - [kubeadm, 1.7.10-00]
runcmd:
 # install certbot
  - sudo snap install core
  - sudo snap refresh core
  - sudo snap install --classic certbot
  - sudo ln -s /snap/bin/certbot /usr/bin/certbot
  - sudo ufw allow 443
  - sudo certbot certonly --standalone -d islafloreanagalapagos.com
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -y update
  - sudo apt-get -y install docker-ce docker-ce-cli containerd.io
  - sudo systemctl enable docker
  # install docker-compose following the guide: https://docs.docker.com/compose/install/
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - mkdir -p  kube
  - cd kube/ 
  - git config --global user.name "smartquailDev"
  - git config --global user.email "smartquail.dev@gmail.com"
  - git clone https://github.com/smartquailprod/qnd30_app_pro.git
  - cd qnode1.2_app/
  - mkdir -p juansilvaphoto.com
  - cd  /kube/qnd11_app_pro/qnd11_app_pro/

 
power_state:
  mode: reboot
  message: Restarting after installing docker & docker-compose